import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import Header3 from './Header3';
import Footer2 from './Footer2';
import { ReactQueryClientProvider } from '@/components/ReactQueryClientProvider';
import { QueryClient } from '@tanstack/react-query';
import { SiteHeader } from '../components/SiteHeader';

const inter = Inter({ subsets: ['latin'] });
const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en" className="dark">
        <body className={inter.className}>
          {/* <Header3 /> */}
          <SiteHeader />
          {children}
          <Footer2 />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
